version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./GopherBackend:/app/backend
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 ソケットを共有
    environment:
      - DISPLAY=${DISPLAY} # ホストの DISPLAY をコンテナに渡す
    working_dir: /app/backend
    command: ["wails", "dev"]

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
